# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-and-test:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/openjdk:17.0
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - persist_to_workspace:
          root: target
          paths: apidocs
      - run:
          name: Test
          command: mvn test
      - run:
          name: Site
          command: mvn site
      - store_artifacts:
          path: target/site
      - codecov/upload

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: target
      - run:
          name: Disable jekyll builds
          command: touch target/apidocs/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@dwerle.fr"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "05:80:35:0b:b5:8d:56:93:e3:57:57:ad:43:03:de:46"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist target/site/apidocs

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
      - docs-deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
